blog/urls.py
from django.urls import path,include
from .views import HomeView,EntryDetial
app_name = 'blog'
urlpatterns = [
    path('',HomeView.as_view(),name='index'),
    path('<int:pk>/',EntryDetial.as_view(),name='entry_detial'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace='blog'))
]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
user_model=get_user_model()

class Entry(models.Model):
    title = models.CharField(max_length=500)
    author = models.ForeignKey(user_model,on_delete=models.SET_NULL,null=True)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)
    
    class Meta:
        verbose_name_plural='entries'
    
    def get_absolute_url(self):
        return reverse('blog:entry_detial',kwargs={'pk':self.pk})
    def __str__(self):
         return self.title

class Comment(models.Model):
    entry = models.ForeignKey(Entry,null=True,on_delete=models.SET_NULL)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)


    def __str__(self) -> str:
        return self.body

blog/forms.py
from django import forms
from .models import Entry,Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

    def __init__(self, *args, **kwargs):
        self.entry = kwargs.pop('entry')   # the blog entry instance
        super().__init__(*args, **kwargs)

    def save(self):
        comment = super().save(commit=False)
        comment.entry = self.entry
        comment.save()
        return comment

blog/views.py
from blog.forms import CommentForm
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,DetailView,CreateView
from . models import Entry
class HomeView(ListView):
    template_name = 'index.html'
    queryset = Entry.objects.order_by('-created_at')
# Create your views here.

class  EntryDetial(CreateView):
    #template_name=
    model=Entry
    template_name='blog/entry_detail.html'
    form_class=CommentForm

    def get_form_kwargs(self):
        kwargs=super().get_form_kwargs()
        kwargs['entry']=self.get_object()
        return kwargs

    def get_context_data(self, **kwargs):
        d=super().get_context_data(**kwargs)
        d['entry']=self.get_object()
        return d
    def get_success_url(self):
        return self.get_object().get_absolute_url()

templates/_entry.html
<article>

    <h2><a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a></h2>

    <p class="subheader">
        <time>{{ entry.modified_at|date }}</time>
    </p>

    <p></p>

    {{ entry.body|linebreaks }}

</article>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>My Blog</title>
    <link rel="stylesheet" href="{% static "css/foundation.css" %}">
</head>
<body>
    <section class="row">
        <header class="large-12 columns">
            <h1>Welcome to My Blog</h1>
            <hr>
        </header>
    </section>

    <section class="row">

        <div class="large-8 columns">
            {% block content %}{% endblock %}
        </div>

        <div class="large-4 columns">
            <h3>About Me</h3>
            <p>I am a Python developer and I like Django.</p>
        </div>

    </section>

</body>
</html>

templates/blog/entry_detail.html
{% extends "base.html" %}

{% block content %}
    {% include "_entry.html" with entry=entry only %}
    <hr>
<h4>Comments</h4>
{% for comment in entry.comment_set.all %}
    <p><em>Posted by {{ comment.name }}</em></p>
    {{ comment|linebreaks }}
{% empty %}
    No comments yet.
{% endfor %}

<h5>Add a comment</h5>
<form method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Create Comment">
</form>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
    {% for entry in entry_list %}
        {% include "_entry.html" with entry=entry only %}
    {% empty %}
        <p>No blog entries yet.</p>
    {% endfor %}
{% endblock content %}